CREATE TABLE [dbo].[Exame] (
    [Codigo]    INT           IDENTITY (1, 1) NOT NULL,
    [Descricao] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([Codigo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);



